### PR TITLE
fix: fix gcloud SDK detection on Windows

### LINKED ISSUE #383: Core: BaseEmulatorHelper fails to detect GCloud installation on Windows
#### Environment details

1. API: Core
2. OS type and version: Windows 10
3. Java version: 11
4. google-cloud-core version(s): 1.94.1

#### Steps to reproduce

  1. Run an emulator on Windows.  For example, using LocalDatastoreHelper
  2. The GCloud installation is not detected, so the emulator runs from a downloaded zip file

#### Code example

```java
LocalDatastoreHelper datastoreHelper = LocalDatastoreHelper.create();
datastoreHelper.start();
```

Look at the processes started.  It will not be the gcloud-based variant, even if gcloud is installed.  You can tell it's the gcloud variant if a python process is started.

#### Stack trace
N/A

#### Any additional information below
In Windows the PATH environment variable is Path (not all uppercase) so this is why it is not detecting the installation.

### PR DESCRIPTION
**Pull request by kevin-wise**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/java-core/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #383

### CODE REVIEW

**Comment by kevin-wise** [comment]
@googlebot I signed it!

**Comment by kevin-wise** [comment]
Cut a local build and tested with my project, it seems to work as intended.

**Review by chingor13 — APPROVED** [review]

**Comment by chingor13** [comment]
Thanks for the patch!

**Comment by kevin-wise** [comment]
@chingor13 thanks for merging.  This is my first time contributing to this project.  What is the release schedule?  Or when can I expect this fix to be released?

**Pull request merged**
